//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Web.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class IdentityCard
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public IdentityCard()
        {
            this.UserProfile = new HashSet<UserProfile>();
        }
    
        public int ID { get; set; }
        public string CPF { get; set; }
        public string RE { get; set; }
        public string RG { get; set; }
        public string PasswordHash { get; set; }
        public Nullable<int> DirectorshipID { get; set; }
        public Nullable<int> HeadID { get; set; }
        public Nullable<int> SectionID { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public bool Active { get; set; }
        public Nullable<System.DateTime> ModifiedDate { get; set; }
        public string UserToken { get; set; }
    
        public virtual Directorship Directorship { get; set; }
        public virtual Head Head { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<UserProfile> UserProfile { get; set; }
    }
}
