//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Web.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Section
    {
        public int SectionID { get; set; }
        public Nullable<int> DirectorshipID { get; set; }
        public Nullable<int> HeadID { get; set; }
        public string Name { get; set; }
        public string Nick { get; set; }
        public bool SectionStatus { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public Nullable<System.DateTime> ModifiedDate { get; set; }
    
        public virtual Directorship Directorship { get; set; }
        public virtual Head Head { get; set; }
    }
}
