//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Web.Data
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class TramitaEntities : DbContext
    {
        public TramitaEntities()
            : base("name=TramitaEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Directorship> Directorship { get; set; }
        public virtual DbSet<Head> Head { get; set; }
        public virtual DbSet<Section> Section { get; set; }
        public virtual DbSet<IdentityCard> IdentityCard { get; set; }
        public virtual DbSet<UserProfile> UserProfile { get; set; }
    }
}
