//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Web.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class UserProfile
    {
        public Nullable<int> IdentityCardID { get; set; }
        public string FirstName { get; set; }
        public string LastName { get; set; }
        public string Email { get; set; }
        public string Phone { get; set; }
        public Nullable<System.DateTime> BirthDate { get; set; }
        public string About { get; set; }
        public string Midia { get; set; }
        public Nullable<System.DateTime> ModifiedDate { get; set; }
    
        public virtual IdentityCard IdentityCard { get; set; }
    }
}
